added candidateImahe and extractBuildImage to Run and Step struct resp
myntra/shuttle-engine pull request #28
Opened 2020-10-13 10:08 UTC by riteshzd

2020-10-13 10:12 UTC, sumanth177 commented on floworch/candidateimage.go
> +	updateRunDetailsToDB(run)
Why updating the entire run?? Can u also post the different also post the before update and after update ??
We though f writing the new function to update into the DB instead of using the same old function

2020-10-28 11:50 UTC, sreeharimohan requested changes
Since we are not really extracting the image name from within the container and pushing the image name as a meta tag, two parameters, `candidateImage` and `extractBuildImage` are redundant.

Use only `candidateImage` in place of `extractBuildImage` at the step level and remove the need for an extra meta tag

2020-10-28 12:25 UTC, sreeharimohan requested changes

2020-10-28 12:25 UTC, sreeharimohan commented on floworch/candidateimage.go
> +	updateRunDetailsToDB(run)
- Rename the function to `updateKey`
- `Value` does not need to a global variable
- reorder the params for better understanding - `(run *types.Run, parameter string, value string,)`
- create a new function which updates the specific key as suggested by @sumanth177

2020-10-28 12:25 UTC, sreeharimohan commented on types/db.go
> +	ExtractBuildImage     bool                    `yaml:"extractBuildImage" gorethink:"extractBuildImage"`
Please remove the `extractBuildImage` parameter

2020-10-28 13:42 UTC, touchps approved these changes

2020-11-27 08:08 UTC, sumanth177 approved these changes

2020-12-02 09:26 UTC, sumanth177 approved these changes

2020-12-02 11:08 UTC, sreeharimohan approved these changes
LGTM

2020-12-02 11:12 UTC, merged